echo Deleting Autogenerated folder
rm -r AutoGenerated

echo Generating CSharp...
java -jar swagger-codegen-cli-3.0.19.jar generate      -i iMusicGenerator.yaml      -l csharp -o ./AutoGenerated/CSharp      -c config.json > outputlog_Csharp.txt || { echo 'FAILED'; exit 1; }

echo Generating Angular...
java -jar swagger-codegen-cli-3.0.19.jar generate      -i iMusicGenerator.yaml      -l typescript-angular -o ./AutoGenerated/Angular > outputlog_Angular.txt || { echo 'FAILED'; exit 1; }

echo Deleting old generated files from solution...
rm ../ClientApp/src/app/core/swagger/*.ts
rm ../ClientApp/src/app/core/swagger/model/*.ts
rm ../ClientApp/src/app/core/swagger/api/*.ts
rm ../Swagger/Model/*.cs

echo Copying new files in the solution...
# copy angular ts files
find ./Autogenerated/Angular -name '*.ts' -maxdepth 1 -exec cp -p '{}' '../ClientApp/src/app/core/swagger' ';' || { echo 'FAILED'; exit 1; }
find ./Autogenerated/Angular/model -name '*.ts' -maxdepth 1 -exec cp -p '{}' '../ClientApp/src/app/core/swagger/model' ';' || { echo 'FAILED'; exit 1; }
find ./Autogenerated/Angular/api -name '*.ts' -maxdepth 1 -exec cp -p '{}' '../ClientApp/src/app/core/swagger/api' ';' || { echo 'FAILED'; exit 1; }

# deleting line that contains 'SwaggerDateConverter' from each cs file
for filename in AutoGenerated/CSharp/src/iMusic.Dto/Model/*.cs; do
    sed '/SwaggerDateConverter;$/d' $filename > $filename.tmp && mv $filename.tmp $filename
done

# copy net core .cs files
find ./Autogenerated/CSharp/src/iMusic.Dto/Model -name '*.cs' -maxdepth 1 -exec cp -p '{}' '../Swagger/Model' ';'  || { echo 'FAILED'; exit 1; }

