swagger: "2.0"
info:
  description: "iMusic"
  version: "1.0.0"
  title: "iMusic DTOs"
  termsOfService: "TODO: add iMusic site ref"
  contact:
    email: "TODO: add iMusic email"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:5001/api"
basePath: "/"
tags:
- name: "user"
  description: "Operations about user"
  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"
consumes:
  - application/json
produces:
  - application/json
schemes:
- "https"
paths:
  login:
    post:
      tags:
        - "login"
      summary: "Login"
      description: "Login request"
      operationId: "login"
      parameters:
        - in: "body"
          name: "body"
          description: "The object sent to login"
          required: true
          schema:
            $ref: "#/definitions/LoginRequest"
      responses:
        default:
          description: "successful operation"
definitions:
  LoginRequest:
    type: object
    description: "This object will be send to login"
    properties:
      emailOrUsername:
        type: string
      password:
        type: string
  LoginResponse:
    type: object
    description: "This object will be send as response if login was successful"
    properties:
      email:
        type: string
      fullName:
        type: string      
      role:
        type: string
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
