swagger: "2.0"
info:
  description: "iMusic"
  version: "1.0.0"
  title: "iMusic DTOs"
  termsOfService: "TODO: add iMusic site ref"
  contact:
    email: "TODO: add iMusic email"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:5001/api"
basePath: "/"
tags:
- name: "user"
  description: "Operations about user"
  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"
consumes:
  - application/json
produces:
  - application/json
schemes:
- "https"
paths:
  songs:
    get:
      tags:
        - "song"
      operationId: "getAllSongs"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: array
            items:
              $ref: '#/definitions/SongDTO'
definitions:
  ArtistDTO:
    type: object
    properties:
      artistId:
        type: number
      name:
        type: string
      bio:
        type: string
      image:
        type: string
  AlbumDTO:
    type: object
    properties:
      albumId:
        type: number
      name:
        type: string
      price:
        type: number
        format: float
      image:
        type: string
      songs:
        type: array
        items:
          $ref: '#/definitions/SongDTO'      
  SongDTO:
    type: object
    properties:
      songId:
        type: number
      name:
        type: string
      length:
        type: string
      price:
        type: number
        format: float
      image:
        type: string
      artists:
        type: array
        items: 
          $ref: '#/definitions/ArtistDTO'
  LoginRequest:
    type: object
    description: "This object will be send to login"
    properties:
      emailOrUsername:
        type: string
      password:
        type: string
  LoginResponse:
    type: object
    description: "This object will be send as response if login was successful"
    properties:
      email:
        type: string
      fullName:
        type: string      
      role:
        type: string
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
