/**
 * iMusic DTOs
 * iMusic
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TODO: add iMusic email
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * This object will be send to login
 */
export interface LoginRequest { 
    emailOrUsername?: string;
    password?: string;
}