/**
 * iMusic DTOs
 * iMusic
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TODO: add iMusic email
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ShoppingCartItemDTO } from './shoppingCartItemDTO';

export interface ShoppingCartDTO { 
    shoppingCartId?: number;
    userId?: number;
    price?: number;
    date?: Date;
    cartitems?: Array<ShoppingCartItemDTO>;
}