/**
 * iMusic DTOs
 * iMusic
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TODO: add iMusic email
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AlbumDTO } from './albumDTO';
import { SongDTO } from './songDTO';

export interface ShoppingCartItemDTO { 
    price?: number;
    albumId?: number;
    album?: AlbumDTO;
    songId?: number;
    song?: SongDTO;
}