/* 
 * iMusic DTOs
 *
 * iMusic
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TODO: add iMusic email
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace iMusic.Dto.Model
{
    /// <summary>
    /// ShoppingCartDTO
    /// </summary>
    [DataContract]
        public partial class ShoppingCartDTO :  IEquatable<ShoppingCartDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ShoppingCartDTO" /> class.
        /// </summary>
        /// <param name="shoppingCartId">shoppingCartId.</param>
        /// <param name="userId">userId.</param>
        /// <param name="price">price.</param>
        /// <param name="date">date.</param>
        /// <param name="cartitems">cartitems.</param>
        public ShoppingCartDTO(decimal? shoppingCartId = default(decimal?), decimal? userId = default(decimal?), float? price = default(float?), DateTime? date = default(DateTime?), List<ShoppingCartItemDTO> cartitems = default(List<ShoppingCartItemDTO>))
        {
            this.ShoppingCartId = shoppingCartId;
            this.UserId = userId;
            this.Price = price;
            this.Date = date;
            this.Cartitems = cartitems;
        }
        
        /// <summary>
        /// Gets or Sets ShoppingCartId
        /// </summary>
        [DataMember(Name="shoppingCartId", EmitDefaultValue=false)]
        public decimal? ShoppingCartId { get; set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [DataMember(Name="userId", EmitDefaultValue=false)]
        public decimal? UserId { get; set; }

        /// <summary>
        /// Gets or Sets Price
        /// </summary>
        [DataMember(Name="price", EmitDefaultValue=false)]
        public float? Price { get; set; }

        /// <summary>
        /// Gets or Sets Date
        /// </summary>
        [DataMember(Name="date", EmitDefaultValue=false)]
        public DateTime? Date { get; set; }

        /// <summary>
        /// Gets or Sets Cartitems
        /// </summary>
        [DataMember(Name="cartitems", EmitDefaultValue=false)]
        public List<ShoppingCartItemDTO> Cartitems { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ShoppingCartDTO {\n");
            sb.Append("  ShoppingCartId: ").Append(ShoppingCartId).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  Cartitems: ").Append(Cartitems).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ShoppingCartDTO);
        }

        /// <summary>
        /// Returns true if ShoppingCartDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of ShoppingCartDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ShoppingCartDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ShoppingCartId == input.ShoppingCartId ||
                    (this.ShoppingCartId != null &&
                    this.ShoppingCartId.Equals(input.ShoppingCartId))
                ) && 
                (
                    this.UserId == input.UserId ||
                    (this.UserId != null &&
                    this.UserId.Equals(input.UserId))
                ) && 
                (
                    this.Price == input.Price ||
                    (this.Price != null &&
                    this.Price.Equals(input.Price))
                ) && 
                (
                    this.Date == input.Date ||
                    (this.Date != null &&
                    this.Date.Equals(input.Date))
                ) && 
                (
                    this.Cartitems == input.Cartitems ||
                    this.Cartitems != null &&
                    input.Cartitems != null &&
                    this.Cartitems.SequenceEqual(input.Cartitems)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ShoppingCartId != null)
                    hashCode = hashCode * 59 + this.ShoppingCartId.GetHashCode();
                if (this.UserId != null)
                    hashCode = hashCode * 59 + this.UserId.GetHashCode();
                if (this.Price != null)
                    hashCode = hashCode * 59 + this.Price.GetHashCode();
                if (this.Date != null)
                    hashCode = hashCode * 59 + this.Date.GetHashCode();
                if (this.Cartitems != null)
                    hashCode = hashCode * 59 + this.Cartitems.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
